ReproductorMultimedia/Controllers/CancionesController.cs
using Logica.Managers;
using Logica.Models;
using Logica.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Plugins;

namespace ReproductorMultimedia.Controllers
{
    public class CancionesController : Controller
    {
        // GET: Canciones/ListaCanciones
        public IActionResult ListaCanciones()
        {
            var lista = CancionesViewModel.ListSongs();
            return View(lista);
        }

        // GET: Canciones/AgregarCancion
        public IActionResult AgregarCancion()
        {
            return View();
        }

        // POST: Canciones/AgregarCancion
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AgregarCancion(int idCancion,string titulo, string artista, string album,string DuracionTexto,IFormFile archivo, Genero genero, int year, IFormFile caratula, string rutaCaratula)
        {
            //Convertimos el texto en TimeSpan y si el formato es incorrecto nos notifica
            if (!TimeSpan.TryParseExact(DuracionTexto, @"m\:ss", null, out var duracion))
            {
                ModelState.AddModelError("DuracionTexto", "Formato inválido, usa mm:ss");
                return View();
            }
            //Comporbamos que el archivo existe
            if (archivo == null || archivo.Length == 0)
            {
                ModelState.AddModelError("ArchivoCancion", "Debes subir un archivo MP3.");
                return View();
            }
            //Preparamos la carpeta para guardar la canción
            var folderPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "CancionesAgregadas");
            if (!Directory.Exists(folderPath))
                Directory.CreateDirectory(folderPath);

            //Generamos un nombre aleatoria único para evitar conflictos

            var uniqueFileName = $"{Guid.NewGuid()}{Path.GetExtension(archivo.FileName)}";
            var fullPath = Path.Combine(folderPath, uniqueFileName);
            var relativePath = $"/CancionesAgregadas/{uniqueFileName}";

            using (var stream = new FileStream(fullPath, FileMode.Create))
            {
                archivo.CopyTo(stream);
            }
            var caratulaFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Caratulas");
            if (!Directory.Exists(caratulaFolder))
                Directory.CreateDirectory(caratulaFolder);

            var caratulaFileName = $"{Guid.NewGuid()}{Path.GetExtension(caratula.FileName)}";
            var caratulaFullPath = Path.Combine(caratulaFolder, caratulaFileName);
            var caratulaRelativePath = $"/Caratulas/{caratulaFileName}";

            using (var stream = new FileStream(caratulaFullPath, FileMode.Create))
            {
                caratula.CopyTo(stream);
            }

            CancionesViewModel.AddSong(
                idCancion,
                titulo,
                artista,
                album,
                duracion,
                0, 0,
                relativePath,
                archivo, // no se guarda el archivo binario
                genero,
                year,
                caratula,
                caratulaRelativePath
            );

            return RedirectToAction("ListaCanciones");
        }


        // GET: Canciones/Edit/5
        public IActionResult Edit(int id)
        {
            return View();
        }

        // POST: Canciones/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, IFormCollection collection)
        {
            return RedirectToAction("Index");
        }

        // GET: Canciones/Delete/5
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var cancion = CancionesViewModel.ObtenerCancionView(id);
            if (cancion == null)
            {
                return NotFound();
            }
            return View(cancion);
        }

        // POST: Canciones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // RemoveCancion is a void method, so no assignment is needed.
                    CancionesViewModel.RemoveCancion(id);
                }
                catch (Exception ex)
                {
                    ViewBag.Error = $"Error al guardar: {ex.Message}";
                }
            }
            return RedirectToAction("ListaCanciones");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ActualizarReproducciones(int id)
        {
            var cancionActualizada = CancionesViewModel.UpdateSong(id);
            if (cancionActualizada != null)
            {
                return Json(new
                {
                    success = true,
                    idCancion = cancionActualizada.idCancion,
                    reproduccionesTotales = cancionActualizada.NumeroReproducciones
                });
            }

            return Json(new { success = false, mensaje = "Canción no encontrada" });
        }




    }
}

ReproductorMultimedia/Controllers/UsuarioController.cs
using Logica.Models;
using Logica.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;
using System.Net.Mail;
using System.Text;

namespace ReproductorMultimedia.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly CorreoService _correoService;
        public UsuarioController(CorreoService correoService)
        {
            _correoService = correoService;
        }

        // GET: UsuarioController
        public ActionResult Administrador()
        {
            var nombreUsuario = HttpContext.Session.GetString("Nombre");
            ViewBag.NombreUsuario = nombreUsuario;

            List<UsuarioViewModel> lista = new List<UsuarioViewModel>();

            lista = UsuarioViewModel.ListUsuarios();
            return View(lista);
        }

        // GET: UsuarioController/Details/5
        public ActionResult Details(int id)
        {
            var prViewModel = UsuarioViewModel.DatosUnUsuario(id);

            if (prViewModel == null)
            {
                //return HttpNotFound();
            }
            return View(prViewModel);
        }

        // GET: UsuarioController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UsuarioController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UsuarioViewModel usu)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    var model = UsuarioViewModel.AddUsuario(usu.idUsuario, usu.Nombre, usu.Email, usu.Password, usu.Estado, usu.fechaBaja, usu.Administrador);
                   // _correoService.EnviarCorreoAlta(model.Email);

                    return RedirectToAction("Administrador");

                }
                catch (Exception ex)
                {

                    ViewBag.Error = $"Error al guardar: {ex.Message}";
                }
            }

            return View(usu);
        }

        // GET: UsuarioController/Edit/5
        public ActionResult Edit(int id)
        {
            UsuarioViewModel prViewModel = UsuarioViewModel.GetUsuario(id);

            if (prViewModel == null)
            {
                //return HttpNotFound();
            }
            return View(prViewModel);
        }

        // POST: UsuarioController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UsuarioViewModel usuario)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    var model = UsuarioViewModel.AddUsuario(usuario.idUsuario, usuario.Nombre, usuario.Email, usuario.Password, usuario.Estado, usuario.fechaBaja, usuario.Administrador);

                    //Si el usuario se da de baja que envíe otro correo
                    if (model.Estado == false)
                    {
                        // EnviarCorreoBaja(model.Email);
                        return RedirectToAction("Administrador");

                    }
                    else
                    {
                       // EnviarCorreoEditado(model.Email);
                        return RedirectToAction("Administrador");
                    }
                }
                catch (Exception ex)
                {
                    ViewBag.Error = $"Error al guardar: {ex.Message}";
                }
            }

            return View(usuario);
        }

        // GET: UsuarioController/Delete/5
        public ActionResult Delete(int id)
        {
            var usuario = UsuarioViewModel.GetUsuario(id);
            if (usuario == null)
                return NotFound();

            return View(usuario);
        }


        // POST: UsuarioController/Delete/5
        [HttpPost, ActionName("DeleteConfirmed")]
        public IActionResult DeleteConfirmed(UsuarioViewModel model)
        {
            if (model.idUsuario == 0)
            {
                // id nulo o no recibido
                return BadRequest("ID de usuario no válido.");
            }

            UsuarioViewModel.RemoveUsuario(model.idUsuario);
            return RedirectToAction("Administrador");
        }


    }
}

ReproductorMultimedia/Views/Usuario/Administrador.cshtml
@model IEnumerable<Logica.ViewModels.UsuarioViewModel>

@{
    ViewData["Title"] = "Administrador";
}
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">

<h1>Administrador: @ViewBag.NombreUsuario</h1>
<p>
    <a id="boton" style="background-color:mediumpurple;" href="@Url.Action("ListaCanciones", "Canciones")" class="btn btn-link">
        <i class="fa-solid fa-music me-2" style="color:black;"></i> Escuchar Canciones
    </a>


    <a id="botonCrear" href="@Url.Action("AgregarCancion", "Canciones")" class="btn btn-link">
        <i class="fa-solid fa-upload" style="color:black;"></i> Subir Canciones
    </a>

    <a id="botonCrearUsuario" href="@Url.Action("Create", "Usuario")" class="btn btn-link">
        <i class="fa-solid fa-user" style="color:black;"></i> Crear Usuario
    </a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>

            <th>
                Fecha de Baja
            </th>
            <th>
                Fecha de Registro
            </th>
            <th>
                Administrador
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.fechaBaja)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fechaRegistro)
                </td>
                <td>
                    @(item.Administrador ? "Sí" : "No")
                </td>
                <td>
                    <a href="@Url.Action("Edit", new { id = item.idUsuario })">
                        <i id="icono" style="color: #e8d15e; font-size: 21px;" class="fa-solid fa-pen-to-square"></i>
                    </a> |

                    <a id="icono" href="@Url.Action("Details", new { id = item.idUsuario })">
                        <i style="color: green; font-size: 21px;" class="fa-regular fa-file-lines"></i>
                    </a>
                    |
                    <a id="icono" href="@Url.Action("Delete", new { id = item.idUsuario })">
                        <i style="color: red; font-size: 21px;" class="fas fa-trash-alt"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>


</table>

<style>
    .table{
        background-color: rgba(255, 255, 255, 0.8);
        border-radius: 10px;
    }
    #boton {
        display: inline-block;
        background-color: mediumpurple;
        color: white;
        padding: 10px 20px;
        border-radius: 30px;
        text-decoration: none;
        font-weight: bold;
        box-shadow: 0 4px 8px rgba(0,0,0,0.2);
        transition: all 0.3s ease;
    }

        #boton i {
            margin-right: 8px;
            transition: transform 0.4s ease;
        }

        #boton:hover {
            background-color: #7b3fd0;
            transform: scale(1.05);
            box-shadow: 0 6px 12px rgba(0,0,0,0.3);
            text-decoration: none;
        }

            #boton:hover i {
                transform: rotate(20deg);
            }

    #botonCrear {
        display: inline-block;
        background-color: #63e78f;
        color: white;
        padding: 10px 20px;
        border-radius: 30px;
        text-decoration: none;
        font-weight: bold;
        box-shadow: 0 4px 8px rgba(0,0,0,0.2);
        transition: all 0.3s ease;
    }

        #botonCrear i {
            margin-right: 8px;
            transition: transform 0.4s ease;
        }

        #botonCrear:hover {
            background-color: #63e78f;
            transform: scale(1.05);
            box-shadow: 0 6px 12px rgba(0,0,0,0.3);
            text-decoration: none;
        }

            #botonCrear:hover i {
                transform: rotate(20deg);
            }

    #botonCrearUsuario {
        display: inline-block;
        background-color: #5ACCCC;
        color: white;
        padding: 10px 20px;
        border-radius: 30px;
        text-decoration: none;
        font-weight: bold;
        box-shadow: 0 4px 8px rgba(0,0,0,0.2);
        transition: all 0.3s ease;
    }

        #botonCrearUsuario i {
            margin-right: 8px;
            transition: transform 0.4s ease;
        }

        #botonCrearUsuario:hover {
            background-color: #5ACCCC;
            transform: scale(1.05);
            box-shadow: 0 6px 12px rgba(0,0,0,0.3);
            text-decoration: none;
        }

            #botonCrearUsuario:hover i {
                transform: rotate(20deg);
            }

    #icono {
        text-decoration: none !important;
        margin: 0 10px;
    }
</style>

ReproductorMultimedia/Views/Usuario/Create.cshtml
@model Logica.ViewModels.UsuarioViewModel

@{
    ViewData["Title"] = "Create";
}


<div class="container d-flex justify-content-center">

    <div class="card p-4 shadow mt-5" style="width: 700px;">
        <h1 class="text-center mb-4">Crear Usuario</h1>

        @using (Html.BeginForm("Create", "Usuario", FormMethod.Post, new { @name = "formCrearUsuario", autocomplete = "off" })) //El autocomplete off desactiva el autocompletado para mayor seguridad
        {
            @Html.AntiForgeryToken()

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label><strong>Nombre</strong></label>
                    @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", placeholder = "Nombre Usuario" } })
                    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                </div>

                <div class="form-group col-md-6">
                    <label><strong>Email</strong></label>
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = "Correo electrónico" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>

                <div class="form-group col-md-6">
                    <label><strong>Contraseña</strong></label>
                    <div class="position-relative">
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", type = "password", id = "myInput", placeholder = "Contraseña", autocomplete = "off" } })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })

                        <span class="position-absolute" style="top: 8px; right: 18px; cursor: pointer;" onclick="togglePassword()">
                            <i id="eyeIcon" class="fa fa-eye"></i>
                        </span>
                    </div>
                </div>

                <div class="form-group col-md-6">
                    <label><strong>¿Eres Administrador?</strong></label>
                    @Html.DropDownListFor(model => model.Administrador, new List<SelectListItem>()
                    {
                        new SelectListItem() { Text = "Sí", Value = "True" },
                                new SelectListItem() { Text = "No", Value = "False" }
                                }, "Selecciona", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Administrador, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="d-flex justify-content-between mt-4">
            <button type="button" class="btn btn-success boton-crear" onclick="mostrarModalCrear()"><i class="fas fa-user-plus pe-2"></i>Crear</button>

            <div class="col-md-3">
                <a href="@Url.Action("Administrador", "Usuario")" class="btn btn-secondary btn-block">
                    <i class="fas fa-arrow-left"></i> Volver
                </a>
            </div>
        </div>

                }
    </div>
    @await Html.PartialAsync("Modal/modalVista")

</div>

<style>
    .card {
        box-shadow: 0 6px 12px rgba(0, 0, 0, 0.2);
        border-radius: 8px;
    }

    .boton-crear:hover {
        background-color: #287538;
        color: white;
        transition: background-color 0.3s ease;
    }

    .switch {
        position: relative;
        display: inline-block;
        width: 35px;
        height: 15px;
        background-color: rgba(0, 0, 0, 0.25);
        border-radius: 22px;
        transition: all 0.3s;
    }

        .switch::after {
            content: '';
            position: absolute;
            width: 11px;
            height: 11px;
            border-radius: 22px;
            background-color: white;
            top: 1px;
            left: 1px;
            transition: all 0.3s;
        }

    input[type='checkbox']:checked + .switch::after {
        transform: translateX(20px);
    }

    input[type='checkbox']:checked + .switch {
        background-color: #7983ff;
    }

    .offscreen {
        position: absolute;
        left: -9999px;
    }
</style>

@section Scripts {
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.5.1.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.3/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/mvc/5.2.7/jquery.validate.unobtrusive.min.js"></script>
}

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<script>
       function togglePassword() {
        var input = document.getElementById("myInput");
        var icon = document.getElementById("eyeIcon");
        if (input.type === "password") {
            input.type = "text";
            icon.classList.remove("fa-eye");
            icon.classList.add("fa-eye-slash");
        } else {
            input.type = "password";
            icon.classList.remove("fa-eye-slash");
            icon.classList.add("fa-eye");
        }
    }
    // Función para mostrar el modal de confirmación antes de crear el usuario. Llama a la función mostrarModalConfirmacion con los parámetros adecuados.
    function mostrarModalCrear() {
        mostrarModalConfirmacion(
            "Confirmar creación",
            "¿Estás seguro de que deseas crear este usuario?",
            "Sí, crear",
            function () {
                document.forms["formCrearUsuario"].submit();
            }
        );
    }

    function mostrarModalConfirmacion(titulo, mensaje, textoBoton, accionCallback) {
        $('#tituloModal').text(titulo);
        $('#mensajeModal').text(mensaje);
        $('#btnConfirmarModal').text(textoBoton);
        $('#btnConfirmarModal').off('click');
        $('#btnConfirmarModal').on('click', function () {
            $('#modalConfirmacion').modal('hide');
            if (typeof accionCallback === 'function') {
                accionCallback();
            }
        });
        $('#modalConfirmacion').modal('show');
    }
</script>

ReproductorMultimedia/Views/Usuario/Delete.cshtml
@model Logica.ViewModels.UsuarioViewModel

@{
    ViewData["Title"] = "Delete";
}

<div class="container d-flex justify-content-center">
    <div class="card p-4 shadow mt-5" style="width: 700px;">

    <h1>Eliminar Usuario</h1>
    <h3>¿Está seguro de que desea eliminar este usuario?</h3>

        <h4>Información del Usuario</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.Nombre)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Nombre)
            </dd>

            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.Email)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Email)
            </dd>

            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.Password)
            </dt>
            <dd class="col-sm-9">
                @{
                    var passwordLength = Model?.Password?.Length ?? 0;
                    var maskedPassword = passwordLength > 0 ? new string('*', passwordLength) : "(Sin contraseña)";
                }
                @maskedPassword
            </dd>

            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.Estado)
            </dt>
            <dd class="col-sm-9">
                @(Model.Estado ? "Activo" : "Inactivo")
            </dd>

            <dt class="col-sm-3">
                Fecha de Baja
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.fechaBaja)
            </dd>

            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.Administrador)
            </dt>
            <dd class="col-sm-9">
                @(Model.Administrador ? "Sí" : "No")
            </dd>
        </dl>

        @using (Html.BeginForm("DeleteConfirmed", "Usuario", FormMethod.Post, new { name = "formEliminarUsuario" }))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.idUsuario)

            <div class="d-flex justify-content-between mt-4">
                <button type="button" class="btn btn-danger" onclick="mostrarModalEliminar()">
                    <i class="fa-solid fa-trash"></i> Eliminar
                </button>

                <div class="col-md-3">
                    <a href="@Url.Action("Administrador", "Usuario")" class="btn btn-secondary btn-block">
                        <i class="fa-solid fa-x"></i> Cancelar
                    </a>
                </div>
            </div>
        }
        @await Html.PartialAsync("Modal/modalVista")
    </div>
</div>
<style>
    .card {
        box-shadow: 0 6px 12px rgba(0, 0, 0, 0.2);
        border-radius: 8px;
    }
</style>
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
<script>
    function myFunction() {
        var x = document.getElementById("myInput");
        if (x.type === "password") {
            x.type = "text";
        } else {
            x.type = "password";
        }
    }
    // Función para mostrar el modal de confirmación antes de crear el usuario. Llama a la función mostrarModalConfirmacion con los parámetros adecuados.
    function mostrarModalEliminar() {
        mostrarModalConfirmacion(
            "Confirmar borrado de usuario",
            "¿Estás seguro de que deseas borrar este usuario?",
            "Sí",
            function () {
                document.forms["formEliminarUsuario"].submit();
            }
        );
    }

    function mostrarModalConfirmacion(titulo, mensaje, textoBoton, accionCallback) {
        $('#tituloModal').text(titulo);
        $('#mensajeModal').text(mensaje);
        $('#btnConfirmarModal').text(textoBoton);
        $('#btnConfirmarModal').off('click');
        $('#btnConfirmarModal').on('click', function () {
            $('#modalConfirmacion').modal('hide');
            if (typeof accionCallback === 'function') {
                accionCallback();
            }
        });
        $('#modalConfirmacion').modal('show');
    }
</script>

ReproductorMultimedia/Views/Usuario/Details.cshtml
@model Logica.ViewModels.UsuarioViewModel

@{
    ViewData["Title"] = "Details";
}
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">

<h1>Detalles</h1>

<div class="card p-4 shadow w-100">
    <h4>Usuario</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class="col-sm-10">
            <span data-password="model.Password">
                @(new string('*', Model.Password != null ? Model.Password.Length : 0))
            </span>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class="col-sm-10">
            @(Model.Estado ? "Activo" : "Inactivo")
        </dd>
        <dt class="col-sm-2">
            Fecha de Baja
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.fechaBaja)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Administrador)
        </dt>
        <dd class="col-sm-10">
            @(Model.Administrador ? "Sí" : "No")
        </dd>
    </dl>

    <div class="mt-4 d-flex justify-content-start gap-3">
        <a href="@Url.Action("Edit", new { id = Model.idUsuario })" class="btn btn-warning shadow-sm">
            <i class="fa-solid fa-pen-to-square me-2"></i> Editar
        </a>
        <a href="@Url.Action("Administrador", "Usuario")" class="btn btn-secondary shadow-sm">
            <i class="fa-solid fa-arrow-left me-2"></i> Volver
        </a>
    </div>

</div>
<style>
    .card {
        box-shadow: 0 6px 12px rgba(0, 0, 0, 0.2);
        border-radius: 8px;
    }

</style>